import Head from 'next/head'
import { Inter } from 'next/font/google'
import DetailedWeather from '@/components/TimeWeatherDetails/DetailedWeather'
import SearchBar from '@/components/SearchBar/SearchBar'
import AsideDetails from '@/components/SearchBar/AsideDetails'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Weather</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={`${inter.className}`}>
        <SearchBar />
        <AsideDetails />
        <DetailedWeather />
      </main>
    </>
  )
}
